#!/usr/bin/env bash

source $(dirname "$0")/env.sh

mkdir -p ${BUILD_DIR}

if [ $# != 1 ]; then
    echo "Usage $0 [target dir]"
    exit 1
else
    TARGET_DIR=$1
fi

require pre_vbox.sh
require pre_docker.sh

rm -rf build

env

cp -r ${TARGET_DIR} ${BUILD_DIR}

docker run -it --rm -v ${BUILD_DIR}:/study_src -e BUILD_RESULT=image.img study_x86_builder /bin/sh

if [ ! -f ${BUILD_RESULT} ]; then
    echo "Build image not found. Check makefile"
    exit 1
fi

VBoxManage storageattach ${VBOX_ENV_NAME} \
    --storagectl Floppy --device 0 --port 0 --port 0 \
    --medium ${BUILD_RESULT}

VBoxManage controlvm ${VBOX_ENV_NAME} poweroff

sleep 1

VBoxManage startvm ${VBOX_ENV_NAME}
