#!/usr/bin/env bash

source $(dirname "$0")/env.sh

mkdir -p ${BUILD_DIR}

if [ $# == 0 ]; then
    echo "Usage $0 [target dir]"
    exit 1
else
    TARGET_DIR=$1
fi

#require pre_vbox.sh
require pre_docker.sh

rm -rf build

cp -r ${TARGET_DIR} ${BUILD_DIR}
sleep 1
docker run -it --rm -v ${BUILD_DIR}:/study_src -e BUILD_RESULT=image.img study_x86_builder

if [ ! -f ${BUILD_RESULT} ]; then
    echo "Build image not found. Check makefile"
    exit 1
fi

# VBoxManage storageattach ${VBOX_ENV_NAME} \
#     --storagectl Floppy --device 0 --port 0 --port 0 \
#     --medium ${BUILD_RESULT}

# VBoxManage controlvm ${VBOX_ENV_NAME} poweroff

# sleep 1

# if [ $# != 1 ]; then
#     VirtualBoxVM --startvm ${VBOX_ENV_NAME} --dbg
# else
#     VBoxManage startvm ${VBOX_ENV_NAME}
# fi

# qemu-system-i386 -fda ${BUILD_RESULT}
qemu-system-i386 -drive file=${BUILD_RESULT},format=raw,index=0,media=disk