#!/usr/bin/env bash

VBOX_ENV_NAME="x86_study"

SCRIPT_DIR=$(cd $(dirname "$0") && pwd)
ROOT_DIR=${SCRIPT_DIR}/..
export BUILD_DIR=${ROOT_DIR}/build
export BUILD_RESULT=${BUILD_DIR}/image.img
TOOLS_DIR=${SCRIPT_DIR}/../tools
TOOLS_OVA=${TOOLS_DIR}/x86_barebone.ova
DOCKER_SRC=${ROOT_DIR}/docker

mkdir -p ${BUILD_DIR}

if [ $# != 1 ]; then
    echo "Usage build.sh [target dir]"
    exit 1
else
    TARGET_DIR=$1
fi

NASM=$(which nasm)
VBOX=$(which VBoxManage)
DOCKER=$(which docker)

if [ "${NASM}" == "" ]; then
    echo "Package nasm not found"
    exit 1
fi

if [ "${VBOX}" == "" ]; then
    echo "Package VBox not found"
    exit 1
fi

if [ "${DOCKER}" == "" ]; then
    echo "Package docker not found"
    exit 1
fi

VBoxManage import ${TOOLS_OVA} --vsys 0 --vmname ${VBOX_ENV_NAME} 1>&- 2>&-

if [ $(docker images -f "reference=study_x86_builder" -q | wc -l) -eq 0 ]; then
    pushd ${DOCKER_SRC}
        docker build --rm -t study_x86_builder .
    popd
fi

rm -rf build
cp -r ${TARGET_DIR} ${BUILD_DIR}

docker run -it --rm -v ${BUILD_DIR}:/study_src -e BUILD_RESULT=image.img study_x86_builder /bin/sh

if [ ! -f ${BUILD_RESULT} ]; then
    echo "Build image not found. Check makefile"
    exit 1
fi

VBoxManage storageattach ${VBOX_ENV_NAME} \
    --storagectl Floppy --device 0 --port 0 --port 0 \
    --medium ${BUILD_RESULT}

VBoxManage controlvm ${VBOX_ENV_NAME} poweroff

sleep 1

VBoxManage startvm ${VBOX_ENV_NAME}
