#!/usr/bin/env bash

source $(dirname "$0")/env.sh

mkdir -p ${BUILD_DIR}

if [ $# != 1 ]; then
    echo "Usage $0 [target dir]"
    exit 1
else
    TARGET_DIR=$1
fi

require pre_docker.sh

rm -rf build
cp -r ${TARGET_DIR} ${BUILD_DIR}

docker run -it --rm \
    -v ${BUILD_DIR}:/study_src \
    -e BUILD_RESULT=image.img \
    --entrypoint "" \
    --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
    study_x86_builder /bin/bash
